/* Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with
the License. You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on
an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the
specific language governing permissions and limitations under the License.

Copyright 2017-2022 the original author or authors.
 */
package org.assertj.vavr.api.soft;
import io.vavr.Lazy;
import io.vavr.Tuple;
import io.vavr.collection.HashMap;
import io.vavr.collection.HashMultimap;
import io.vavr.collection.HashSet;
import io.vavr.collection.List;
import io.vavr.collection.Map;
import io.vavr.collection.Multimap;
import io.vavr.collection.Seq;
import io.vavr.collection.Set;
import io.vavr.control.Either;
import io.vavr.control.Option;
import io.vavr.control.Try;
import io.vavr.control.Validation;
import org.assertj.core.api.Assertions;
import org.assertj.core.api.Condition;
import org.opentest4j.MultipleFailuresError;
import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.data.Index.atIndex;
class SoftVavrAssertionsHelper {
    static void verifyErrors(java.lang.Double evaluatedVal, org.opentest4j.MultipleFailuresError e) {
        io.vavr.collection.List<java.lang.String> errors = io.vavr.collection.List.ofAll(e.getFailures()).map(java.lang.Object::toString);
        org.assertj.vavr.api.VavrAssertions.assertThat(errors).hasSize(107);
        org.assertj.core.api.Assertions.assertThat(errors.get(0)).contains(java.lang.String.format("java.lang.AssertionError: %nExpecting:%n  <Some(value)>%nto contain:%n  <\"\">%nbut did not."));
        org.assertj.core.api.Assertions.assertThat(errors.get(1)).contains(java.lang.String.format("java.lang.AssertionError: %nExpecting:%n <Some>%nto contain a value that is an instance of:%n <java.lang.Integer>%nbut did contain an instance of:%n <java.lang.String>"));
        org.assertj.core.api.Assertions.assertThat(errors.get(2)).contains(java.lang.String.format("java.lang.AssertionError: %nExpecting:%n  <Some(value)>%nto contain the instance (i.e. compared with ==):%n  <\"value\">%nbut did not."));
        org.assertj.core.api.Assertions.assertThat(errors.get(3)).contains(java.lang.String.format("org.opentest4j.AssertionFailedError: %nexpected: \"xyz\"%n but was: \"value\""));
        org.assertj.core.api.Assertions.assertThat(errors.get(4)).contains(java.lang.String.format("java.lang.AssertionError: %nExpecting an Option to be empty but was <\"value\">."));
        org.assertj.core.api.Assertions.assertThat(errors.get(5)).contains(java.lang.String.format("java.lang.AssertionError: %nExpecting Option to contain a value but it didn't."));
        org.assertj.core.api.Assertions.assertThat(errors.get(6)).contains(java.lang.String.format(("java.lang.AssertionError: %nExpecting Lazy to be not evaluated but it was <Lazy(" + evaluatedVal) + ")>"));
        org.assertj.core.api.Assertions.assertThat(errors.get(7)).contains(java.lang.String.format("java.lang.AssertionError: %nExpecting Lazy to be evaluated, but it was not"));
        org.assertj.core.api.Assertions.assertThat(errors.get(8)).startsWith(java.lang.String.format("java.lang.AssertionError: %nExpecting all elements of:%n  HashSet(Frodo, Bilbo)%nto satisfy given requirements, but these elements did not:%n%n\"Bilbo\"%nerror: %nExpecting actual:%n  \"Bilbo\"%nto start with:%n  \"F\"%n"));
        org.assertj.core.api.Assertions.assertThat(errors.get(9)).contains(java.lang.String.format("java.lang.AssertionError: %nExpected size: 1 but was: 2 in:%nHashSet(Frodo, Bilbo)"));
        org.assertj.core.api.Assertions.assertThat(errors.get(10)).contains(java.lang.String.format("java.lang.AssertionError: %nExpecting empty but was: HashSet(Frodo, Bilbo)"));
        org.assertj.core.api.Assertions.assertThat(errors.get(11)).contains(java.lang.String.format("java.lang.AssertionError: %nExpecting actual:%n  \"Frodo\"%nat index 1 but found:%n  \"Bilbo\"%nin:%n  List(Frodo, Bilbo)%n"));
        org.assertj.core.api.Assertions.assertThat(errors.get(12)).contains(java.lang.String.format("java.lang.AssertionError: %nExpecting actual:%n  List(Frodo, Bilbo)%nnot to contain:%n  \"Frodo\"%nat index 0%n"));
        org.assertj.core.api.Assertions.assertThat(errors.get(13)).contains(java.lang.String.format("java.lang.AssertionError: %nExpecting:%n <\"Bilbo\">%nat index <1> to have:%n <starts with some>%nin:%n <List(Frodo, Bilbo)>%n"));
        org.assertj.core.api.Assertions.assertThat(errors.get(14)).contains(java.lang.String.format("java.lang.AssertionError: %nsequence is not sorted because element 0:%n <\"Frodo\">%nis not less or equal than element 1:%n <\"Bilbo\">%nsequence was:%n <List(Frodo, Bilbo)>"));
        org.assertj.core.api.Assertions.assertThat(errors.get(15)).contains(java.lang.String.format("java.lang.AssertionError: %nsequence is not sorted according to INSTANCE comparator because element 0:%n <\"Frodo\">%nis not less or equal than element 1:%n <\"Bilbo\">%nsequence was:%n <List(Frodo, Bilbo)>"));
        org.assertj.core.api.Assertions.assertThat(errors.get(16)).contains(java.lang.String.format("java.lang.AssertionError: %nExpecting actual:%n  \"Frodo\"%nto start with:%n  \"some\"%n"));
        org.assertj.core.api.Assertions.assertThat(errors.get(17)).contains(java.lang.String.format("java.lang.AssertionError: %nExpecting a Validation to be invalid but was valid <\"ok\">."));
        org.assertj.core.api.Assertions.assertThat(errors.get(18)).contains(java.lang.String.format("java.lang.AssertionError: %nExpecting:%n  <Valid(ok)>%nto contain:%n  <\"not ok\">%nbut did not."));
        org.assertj.core.api.Assertions.assertThat(errors.get(19)).contains(java.lang.String.format("java.lang.AssertionError: %nExpecting:%n <Valid>%nto contain a value that is an instance of:%n <java.lang.Integer>%nbut did contain an instance of:%n <java.lang.String>"));
        org.assertj.core.api.Assertions.assertThat(errors.get(20)).contains(java.lang.String.format("java.lang.AssertionError: %nExpecting:%n  <Valid(ok)>%nto contain the instance (i.e. compared with ==):%n  <\"not ok\">%nbut did not."));
        org.assertj.core.api.Assertions.assertThat(errors.get(21)).contains(java.lang.String.format("java.lang.AssertionError: %nExpecting:%n  <Valid(ok)>%nto contain the instance (i.e. compared with ==):%n  <\"not ok\">%nbut did not."));
        org.assertj.core.api.Assertions.assertThat(errors.get(22)).contains(java.lang.String.format("java.lang.AssertionError: %nExpecting:%n  <Valid(ok)>%nto contain the instance (i.e. compared with ==):%n  <\"not ok\">%nbut did not."));
        org.assertj.core.api.Assertions.assertThat(errors.get(23)).contains(java.lang.String.format("java.lang.AssertionError: %nExpecting a Validation to be valid but was invalid <\"not ok\">."));
        org.assertj.core.api.Assertions.assertThat(errors.get(24)).contains(java.lang.String.format("java.lang.AssertionError: %nExpecting:%n  <Invalid(not ok)>%nto contain:%n  <\"ok\">%nbut did not."));
        org.assertj.core.api.Assertions.assertThat(errors.get(25)).contains(java.lang.String.format("java.lang.AssertionError: %nExpecting:%n <Invalid>%nto contain a value that is an instance of:%n <java.lang.Integer>%nbut did contain an instance of:%n <java.lang.String>"));
        org.assertj.core.api.Assertions.assertThat(errors.get(26)).contains(java.lang.String.format("java.lang.AssertionError: %nExpecting:%n  <Invalid(not ok)>%nto contain the instance (i.e. compared with ==):%n  <\"ok\">%nbut did not."));
        org.assertj.core.api.Assertions.assertThat(errors.get(27)).contains(java.lang.String.format("java.lang.AssertionError: %nExpecting:%n  <Invalid(not ok)>%nto contain the instance (i.e. compared with ==):%n  <\"ok\">%nbut did not."));
        org.assertj.core.api.Assertions.assertThat(errors.get(28)).contains(java.lang.String.format("java.lang.AssertionError: %nExpecting:%n  <Invalid(not ok)>%nto contain the instance (i.e. compared with ==):%n  <\"ok\">%nbut did not."));
        org.assertj.core.api.Assertions.assertThat(errors.get(29)).contains(java.lang.String.format("java.lang.AssertionError: %nExpecting Try to be a Failure, but wasn't"));
        org.assertj.core.api.Assertions.assertThat(errors.get(30)).contains(java.lang.String.format("java.lang.AssertionError: %nExpecting:%n  <Success(ok)>%nto contain:%n  <\"not ok\">%nbut did not."));
        org.assertj.core.api.Assertions.assertThat(errors.get(31)).contains(java.lang.String.format("java.lang.AssertionError: %nExpecting:%n  <Success(ok)>%nto contain the instance (i.e. compared with ==):%n  <\"nok\">%nbut did not."));
        org.assertj.core.api.Assertions.assertThat(errors.get(32)).contains(java.lang.String.format("java.lang.AssertionError: %nExpecting:%n  <Success(ok)>%nto contain the instance (i.e. compared with ==):%n  <\"nok\">%nbut did not."));
        org.assertj.core.api.Assertions.assertThat(errors.get(33)).contains(java.lang.String.format("java.lang.AssertionError: %nExpecting:%n <Success>%nto contain a value that is an instance of:%n <java.lang.Integer>%nbut did contain an instance of:%n <java.lang.String>"));
        org.assertj.core.api.Assertions.assertThat(errors.get(34)).contains(java.lang.String.format("java.lang.AssertionError: %nExpecting:%n  <Success(ok)>%nto contain the instance (i.e. compared with ==):%n  <\"not same\">%nbut did not."));
        org.assertj.core.api.Assertions.assertThat(errors.get(35)).contains(java.lang.String.format("java.lang.AssertionError: %nExpecting actual:%n  \"ok\"%nto be starts with some"));
        org.assertj.core.api.Assertions.assertThat(errors.get(36)).contains(java.lang.String.format("java.lang.AssertionError: %nExpecting actual:%n  \"ok\"%nto start with:%n  \"some\"%n"));
        org.assertj.core.api.Assertions.assertThat(errors.get(37)).startsWith(java.lang.String.format("java.lang.AssertionError: %nExpecting Try to be a Success, but was a Failure:%n- exception class: java.lang.IllegalStateException%n- message: not ok"));
        org.assertj.core.api.Assertions.assertThat(errors.get(38)).startsWith(java.lang.String.format("java.lang.AssertionError: %nExpecting actual throwable to be an instance of:%n  java.lang.NullPointerException%nbut was:%n  java.lang.IllegalStateException: not ok"));
        org.assertj.core.api.Assertions.assertThat(errors.get(39)).startsWith(java.lang.String.format("org.opentest4j.AssertionFailedError: %nExpecting message to be:%n  \"another message\"%nbut was:%n  \"not ok\""));
        org.assertj.core.api.Assertions.assertThat(errors.get(40)).contains(java.lang.String.format("java.lang.AssertionError: %nExpecting an Either to be left but was <Right(2)>."));
        org.assertj.core.api.Assertions.assertThat(errors.get(41)).contains(java.lang.String.format("java.lang.AssertionError: %nExpecting:%n  <Right(2)>%nto contain:%n  <1> on the [RIGHT]%nbut did not."));
        org.assertj.core.api.Assertions.assertThat(errors.get(42)).contains(java.lang.String.format("java.lang.AssertionError: %nExpecting:%n  <Right(2)>%nto contain the instance (i.e. compared with ==):%n  <1>%nbut did not."));
        org.assertj.core.api.Assertions.assertThat(errors.get(43)).contains(java.lang.String.format("java.lang.AssertionError: %nExpecting:%n <Right>%nto contain a value that is an instance of:%n <java.lang.String>%nbut did contain an instance of:%n <java.lang.Integer>"));
        org.assertj.core.api.Assertions.assertThat(errors.get(44)).contains(java.lang.String.format("org.opentest4j.AssertionFailedError: %nexpected: 0%n but was: 2"));
        org.assertj.core.api.Assertions.assertThat(errors.get(45)).contains(java.lang.String.format("java.lang.AssertionError: %nExpecting:%n  <Right(2)>%nto contain:%n  <3> on the [RIGHT]%nbut did not."));
        org.assertj.core.api.Assertions.assertThat(errors.get(46)).contains(java.lang.String.format("java.lang.AssertionError: %nExpecting:%n  <Right(2)>%nto contain:%n  <3> on the [RIGHT]%nbut did not."));
        org.assertj.core.api.Assertions.assertThat(errors.get(47)).contains(java.lang.String.format("java.lang.AssertionError: %nExpecting an Either to be right but was <Left(not ok)>."));
        org.assertj.core.api.Assertions.assertThat(errors.get(48)).contains(java.lang.String.format("java.lang.AssertionError: %nExpecting:%n  <Left(not ok)>%nto contain:%n  <\"ok\"> on the [LEFT]%nbut did not."));
        org.assertj.core.api.Assertions.assertThat(errors.get(49)).contains(java.lang.String.format("java.lang.AssertionError: %nExpecting:%n  <Left(not ok)>%nto contain the instance (i.e. compared with ==):%n  <\"ok\">%nbut did not."));
        org.assertj.core.api.Assertions.assertThat(errors.get(50)).contains(java.lang.String.format("java.lang.AssertionError: %nExpecting:%n <Left>%nto contain a value that is an instance of:%n <java.lang.Integer>%nbut did contain an instance of:%n <java.lang.String>"));
        org.assertj.core.api.Assertions.assertThat(errors.get(51)).contains(java.lang.String.format("java.lang.AssertionError: %nExpected size: 1 but was: 6 in:%n\"not ok\""));
        org.assertj.core.api.Assertions.assertThat(errors.get(52)).contains(java.lang.String.format("java.lang.AssertionError: %nExpecting an Either to be left but was <Right(2)>."));
        org.assertj.core.api.Assertions.assertThat(errors.get(53)).contains(java.lang.String.format("java.lang.AssertionError: %nExpecting an Either to be left but was <Right(2)>."));
        org.assertj.core.api.Assertions.assertThat(errors.get(54)).contains(java.lang.String.format("java.lang.AssertionError: %nExpecting actual not to be empty"));
        org.assertj.core.api.Assertions.assertThat(errors.get(55)).contains(java.lang.String.format("java.lang.AssertionError: %nExpecting empty but was: HashMap((Frodo, Baggins))"));
        org.assertj.core.api.Assertions.assertThat(errors.get(56)).startsWith(java.lang.String.format("java.lang.AssertionError: %nExpecting actual:%n  \"Frodo\"%nto start with:%n  \"key\""));
        org.assertj.core.api.Assertions.assertThat(errors.get(57)).contains(java.lang.String.format("java.lang.AssertionError: %nExpecting actual:%n  HashMap((Frodo, Baggins))%nto contain at least one of the following elements:%n  [(Bilbo, Baggins)]%nbut none were found"));
        org.assertj.core.api.Assertions.assertThat(errors.get(58)).contains(java.lang.String.format("java.lang.AssertionError: %nExpecting HashMap:%n  HashMap((Frodo, Baggins))%nto contain:%n  [(Peregrin, Took)]%nbut could not find the following element(s):%n  HashSet((Peregrin, Took))%n"));
        org.assertj.core.api.Assertions.assertThat(errors.get(59)).contains(java.lang.String.format("java.lang.AssertionError: %nExpecting HashMap:%n  HashMap((Frodo, Baggins))%nto contain:%n  [(Bilbo, Baggins)]%nbut could not find the following element(s):%n  HashSet((Bilbo, Baggins))%n"));
        org.assertj.core.api.Assertions.assertThat(errors.get(60)).contains(java.lang.String.format("java.lang.AssertionError: %nExpecting HashMap:%n  HashMap((Frodo, Baggins))%nto contain:%n  [(Bilbo, Baggins)]%nbut could not find the following element(s):%n  HashSet((Bilbo, Baggins))%n"));
        org.assertj.core.api.Assertions.assertThat(errors.get(61)).contains(java.lang.String.format("java.lang.AssertionError: %nExpecting actual:%n  HashMap((Frodo, Baggins))%nto contain exactly (and in same order):%n  List((Peregrin, Took))%nbut some elements were not found:%n  LinkedHashMap((Peregrin, Took))%nand others were not expected:%n  HashMap((Frodo, Baggins))%n"));
        org.assertj.core.api.Assertions.assertThat(errors.get(62)).contains(java.lang.String.format("java.lang.AssertionError: %nExpecting actual:%n  HashMap((Frodo, Baggins))%nto contain key:%n  \"Peregrin\""));
        org.assertj.core.api.Assertions.assertThat(errors.get(63)).contains(java.lang.String.format("java.lang.AssertionError: %nExpecting actual:%n  HashMap((Frodo, Baggins))%nto contain keys:%n  [\"Bilbo\", \"Peregrin\"]"));
        org.assertj.core.api.Assertions.assertThat(errors.get(64)).contains(java.lang.String.format("java.lang.AssertionError: %nExpecting actual:%n  HashMap((Frodo, Baggins))%nto contain value:%n  \"Took\""));
        org.assertj.core.api.Assertions.assertThat(errors.get(65)).contains(java.lang.String.format("java.lang.AssertionError: %nExpecting actual:%n  HashMap((Frodo, Baggins))%nto contain values:%n  [\"Took\", \"Brandybuck\"]"));
        org.assertj.core.api.Assertions.assertThat(errors.get(66)).contains(java.lang.String.format("java.lang.AssertionError: %nExpecting%n  HashMap((Frodo, Baggins))%nnot to contain%n  [(Frodo, Baggins)]%nbut found%n  HashSet((Frodo, Baggins))%n"));
        org.assertj.core.api.Assertions.assertThat(errors.get(67)).contains(java.lang.String.format("java.lang.AssertionError: %nExpecting%n  HashMap((Frodo, Baggins))%nnot to contain%n  [(Frodo, Baggins)]%nbut found%n  HashSet((Frodo, Baggins))%n"));
        org.assertj.core.api.Assertions.assertThat(errors.get(68)).contains(java.lang.String.format("java.lang.AssertionError: %nExpecting actual:%n  HashMap((Frodo, Baggins))%nnot to contain key:%n  \"Frodo\""));
        org.assertj.core.api.Assertions.assertThat(errors.get(69)).contains(java.lang.String.format("java.lang.AssertionError: %nExpecting actual:%n  HashMap((Frodo, Baggins))%nnot to contain key:%n  \"Frodo\""));
        org.assertj.core.api.Assertions.assertThat(errors.get(70)).contains(java.lang.String.format("java.lang.AssertionError: %nExpecting actual:%n  HashMap((Frodo, Baggins))%nnot to contain value:%n  \"Baggins\""));
        org.assertj.core.api.Assertions.assertThat(errors.get(71)).contains(java.lang.String.format("java.lang.AssertionError: %nExpecting:%n  <HashMap((Frodo, Baggins))>%nnot to contain values:%n  <[\"Baggins\"]>"));
        org.assertj.core.api.Assertions.assertThat(errors.get(72)).startsWith(java.lang.String.format("java.lang.AssertionError: %nExpecting elements:%n  Some(Baggins)%nof%n  HashMap((Frodo, Baggins))%nto be starts with some"));
        org.assertj.core.api.Assertions.assertThat(errors.get(73)).contains(java.lang.String.format("java.lang.AssertionError: %nActual and expected should have same size but actual size is:%n  1%nwhile expected size is:%n  0%nActual was:%n  HashMap((Frodo, Baggins))%nExpected was:%n  []"));
        org.assertj.core.api.Assertions.assertThat(errors.get(74)).contains(java.lang.String.format("java.lang.AssertionError: %nActual and expected should have same size but actual size is:%n  1%nwhile expected size is:%n  0%nActual was:%n  HashMap((Frodo, Baggins))%nExpected was:%n  List()"));
        org.assertj.core.api.Assertions.assertThat(errors.get(75)).contains(java.lang.String.format("java.lang.AssertionError: %nExpected size: 0 but was: 1 in:%nHashMap((Frodo, Baggins))"));
        org.assertj.core.api.Assertions.assertThat(errors.get(76)).contains(java.lang.String.format("java.lang.AssertionError: %nExpecting size of:%n  HashMap((Frodo, Baggins))%nto be greater than 2 but was 1"));
        org.assertj.core.api.Assertions.assertThat(errors.get(77)).contains(java.lang.String.format("java.lang.AssertionError: %nExpecting size of:%n  HashMap((Frodo, Baggins))%nto be less than 1 but was 1"));
        org.assertj.core.api.Assertions.assertThat(errors.get(78)).contains(java.lang.String.format("org.opentest4j.AssertionFailedError: %nexpected: HashMap()%n but was: HashMap((Frodo, Baggins))"));
        org.assertj.core.api.Assertions.assertThat(errors.get(79)).contains(java.lang.String.format("java.lang.AssertionError: %nExpecting actual:%n  HashMap((Frodo, Baggins))%nnot to be equal to:%n  HashMap((Frodo, Baggins))%n"));
        org.assertj.core.api.Assertions.assertThat(errors.get(80)).contains(java.lang.String.format("java.lang.AssertionError: %nExpecting null or empty but was: HashMap((Frodo, Baggins))"));
        org.assertj.core.api.Assertions.assertThat(errors.get(81)).contains(java.lang.String.format("java.lang.AssertionError: %nExpecting actual not to be empty"));
        org.assertj.core.api.Assertions.assertThat(errors.get(82)).contains(java.lang.String.format("java.lang.AssertionError: %nExpecting empty but was: HashMultimap[List]((Frodo, Baggins))"));
        org.assertj.core.api.Assertions.assertThat(errors.get(83)).startsWith(java.lang.String.format("java.lang.AssertionError: %nExpecting actual:%n  \"Frodo\"%nto start with:%n  \"key\""));
        org.assertj.core.api.Assertions.assertThat(errors.get(84)).contains(java.lang.String.format("java.lang.AssertionError: %nExpecting actual:%n  HashMultimap[List]((Frodo, Baggins))%nto contain at least one of the following elements:%n  [(Bilbo, Baggins)]%nbut none were found"));
        org.assertj.core.api.Assertions.assertThat(errors.get(85)).contains(java.lang.String.format("java.lang.AssertionError: %nExpecting HashMultimap:%n  HashMultimap[List]((Frodo, Baggins))%nto contain:%n  [(Peregrin, Took)]%nbut could not find the following element(s):%n  HashSet((Peregrin, Took))%n"));
        org.assertj.core.api.Assertions.assertThat(errors.get(86)).contains(java.lang.String.format("java.lang.AssertionError: %nExpecting HashMultimap:%n  HashMultimap[List]((Frodo, Baggins))%nto contain:%n  [(Bilbo, Baggins)]%nbut could not find the following element(s):%n  HashSet((Bilbo, Baggins))%n"));
        org.assertj.core.api.Assertions.assertThat(errors.get(87)).contains(java.lang.String.format("java.lang.AssertionError: %nExpecting HashMultimap:%n  HashMultimap[List]((Frodo, Baggins))%nto contain:%n  [(Bilbo, Baggins)]%nbut could not find the following element(s):%n  HashSet((Bilbo, Baggins))%n"));
        org.assertj.core.api.Assertions.assertThat(errors.get(88)).contains(java.lang.String.format("java.lang.AssertionError: %nExpecting actual:%n  HashMultimap[List]((Frodo, Baggins))%nto contain exactly (and in same order):%n  List((Peregrin, Took))%nbut some elements were not found:%n  LinkedHashMultimap[List]((Peregrin, Took))%nand others were not expected:%n  HashMultimap[List]((Frodo, Baggins))%n"));
        org.assertj.core.api.Assertions.assertThat(errors.get(89)).contains(java.lang.String.format("java.lang.AssertionError: %nExpecting actual:%n  HashMultimap[List]((Frodo, Baggins))%nto contain key:%n  \"Peregrin\""));
        org.assertj.core.api.Assertions.assertThat(errors.get(90)).contains(java.lang.String.format("java.lang.AssertionError: %nExpecting actual:%n  HashMultimap[List]((Frodo, Baggins))%nto contain keys:%n  [\"Bilbo\", \"Peregrin\"]"));
        org.assertj.core.api.Assertions.assertThat(errors.get(91)).contains(java.lang.String.format("java.lang.AssertionError: %nExpecting actual:%n  HashMultimap[List]((Frodo, Baggins))%nto contain value:%n  \"Took\""));
        org.assertj.core.api.Assertions.assertThat(errors.get(92)).contains(java.lang.String.format("java.lang.AssertionError: %nExpecting actual:%n  HashMultimap[List]((Frodo, Baggins))%nto contain values:%n  [\"Took\", \"Brandybuck\"]"));
        org.assertj.core.api.Assertions.assertThat(errors.get(93)).contains(java.lang.String.format("java.lang.AssertionError: %nExpecting%n  HashMultimap[List]((Frodo, Baggins))%nnot to contain%n  [(Frodo, Baggins)]%nbut found%n  HashSet((Frodo, Baggins))%n"));
        org.assertj.core.api.Assertions.assertThat(errors.get(94)).contains(java.lang.String.format("java.lang.AssertionError: %nExpecting%n  HashMultimap[List]((Frodo, Baggins))%nnot to contain%n  [(Frodo, Baggins)]%nbut found%n  HashSet((Frodo, Baggins))%n"));
        org.assertj.core.api.Assertions.assertThat(errors.get(95)).contains(java.lang.String.format("java.lang.AssertionError: %nExpecting actual:%n  HashMultimap[List]((Frodo, Baggins))%nnot to contain key:%n  \"Frodo\""));
        org.assertj.core.api.Assertions.assertThat(errors.get(96)).contains(java.lang.String.format("java.lang.AssertionError: %nExpecting actual:%n  HashMultimap[List]((Frodo, Baggins))%nnot to contain key:%n  \"Frodo\""));
        org.assertj.core.api.Assertions.assertThat(errors.get(97)).contains(java.lang.String.format("java.lang.AssertionError: %nExpecting actual:%n  HashMultimap[List]((Frodo, Baggins))%nnot to contain value:%n  \"Baggins\""));
        org.assertj.core.api.Assertions.assertThat(errors.get(98)).contains(java.lang.String.format("java.lang.AssertionError: %nExpecting:%n  <HashMultimap[List]((Frodo, Baggins))>%nnot to contain values:%n  <[\"Baggins\"]>"));
        org.assertj.core.api.Assertions.assertThat(errors.get(99)).startsWith(java.lang.String.format("java.lang.AssertionError: %nExpecting elements:%n  Some(List(Baggins))%nof%n  HashMultimap[List]((Frodo, Baggins))%nto be starts with some"));
        org.assertj.core.api.Assertions.assertThat(errors.get(100)).contains(java.lang.String.format("java.lang.AssertionError: %nActual and expected should have same size but actual size is:%n  1%nwhile expected size is:%n  0%nActual was:%n  HashMultimap[List]((Frodo, Baggins))%nExpected was:%n  []"));
        org.assertj.core.api.Assertions.assertThat(errors.get(101)).contains(java.lang.String.format("java.lang.AssertionError: %nActual and expected should have same size but actual size is:%n  1%nwhile expected size is:%n  0%nActual was:%n  HashMultimap[List]((Frodo, Baggins))%nExpected was:%n  List()"));
        org.assertj.core.api.Assertions.assertThat(errors.get(102)).contains(java.lang.String.format("java.lang.AssertionError: %nExpected size: 0 but was: 1 in:%nHashMultimap[List]((Frodo, Baggins))"));
        org.assertj.core.api.Assertions.assertThat(errors.get(103)).contains(java.lang.String.format("java.lang.AssertionError: %nExpecting size of:%n  HashMultimap[List]((Frodo, Baggins))%nto be greater than 2 but was 1"));
        org.assertj.core.api.Assertions.assertThat(errors.get(104)).contains(java.lang.String.format("java.lang.AssertionError: %nExpecting size of:%n  HashMultimap[List]((Frodo, Baggins))%nto be less than 1 but was 1"));
        org.assertj.core.api.Assertions.assertThat(errors.get(105)).contains(java.lang.String.format("org.opentest4j.AssertionFailedError: %nexpected: HashMap()%n but was: HashMultimap[List]((Frodo, Baggins))"));
        org.assertj.core.api.Assertions.assertThat(errors.get(106)).contains(java.lang.String.format("java.lang.AssertionError: %nExpecting null or empty but was: HashMultimap[List]((Frodo, Baggins))"));
    }

    static void runSoftlyAssertions(io.vavr.Lazy<java.lang.Double> evaluated, org.assertj.vavr.api.soft.SoftVavrAssertions softly) {
        io.vavr.control.Option<java.lang.String> option = io.vavr.control.Option.some("value");
        softly.assertThat(option).contains("");
        softly.assertThat(option).containsInstanceOf(java.lang.Integer.class);
        softly.assertThat(option).containsSame(new java.lang.String("value"));
        softly.assertThat(option).hasValueSatisfying(v -> org.assertj.core.api.Assertions.assertThat(v).isEqualTo("xyz"));
        softly.assertThat(option).isEmpty();
        softly.assertThat(io.vavr.control.Option.none()).isDefined();
        softly.assertThat(evaluated).isNotEvaluated();
        io.vavr.Lazy<java.lang.Double> notEvaluated = io.vavr.Lazy.of(java.lang.Math::random);
        softly.assertThat(notEvaluated).isEvaluated();
        io.vavr.collection.Set<java.lang.String> set = io.vavr.collection.HashSet.of("Bilbo", "Frodo");
        softly.assertThat(set).allSatisfy(name -> assertThat(name).startsWith("F"));
        softly.assertThat(set).hasSize(1);
        softly.assertThat(set).isEmpty();
        io.vavr.collection.Seq<java.lang.String> seq = io.vavr.collection.List.of("Frodo", "Bilbo");
        softly.assertThat(seq).contains("Frodo", org.assertj.core.data.Index.atIndex(1));
        softly.assertThat(seq).doesNotContain("Frodo", org.assertj.core.data.Index.atIndex(0));
        softly.assertThat(seq).has(new org.assertj.core.api.Condition<>(str -> str.startsWith("some"), "starts with some"), org.assertj.core.data.Index.atIndex(1));
        softly.assertThat(seq).isSorted();
        softly.assertThat(seq).isSortedAccordingTo(java.util.Comparator.naturalOrder());
        softly.assertThat(seq).satisfies(str -> assertThat(str).startsWith("some"), org.assertj.core.data.Index.atIndex(0));
        io.vavr.control.Validation<java.lang.String, java.lang.String> valid = io.vavr.control.Validation.valid("ok");
        softly.assertThat(valid).isInvalid();
        softly.assertThat(valid).containsValid("not ok");
        softly.assertThat(valid).containsValidInstanceOf(java.lang.Integer.class);
        softly.assertThat(valid).containsValidSame("not ok");
        softly.assertThat(valid).usingValueComparator(java.util.Comparator.naturalOrder()).containsValidSame("not ok");
        softly.assertThat(valid).usingFieldByFieldValueComparator().containsValidSame("not ok");
        io.vavr.control.Validation<java.lang.String, java.lang.String> invalid = io.vavr.control.Validation.invalid("not ok");
        softly.assertThat(invalid).isValid();
        softly.assertThat(invalid).containsInvalid("ok");
        softly.assertThat(invalid).containsInvalidInstanceOf(java.lang.Integer.class);
        softly.assertThat(invalid).containsInvalidSame("ok");
        softly.assertThat(invalid).usingValueComparator(java.util.Comparator.naturalOrder()).containsInvalidSame("ok");
        softly.assertThat(invalid).usingFieldByFieldValueComparator().containsInvalidSame("ok");
        io.vavr.control.Try<java.lang.String> success = io.vavr.control.Try.success("ok");
        softly.assertThat(success).isFailure();
        softly.assertThat(success).contains("not ok");
        softly.assertThat(success).usingValueComparator(java.util.Comparator.naturalOrder()).containsSame("nok");
        softly.assertThat(success).usingFieldByFieldValueComparator().containsSame("nok");
        softly.assertThat(success).containsInstanceOf(java.lang.Integer.class);
        softly.assertThat(success).containsSame("not same");
        softly.assertThat(success).hasValueSatisfying(new org.assertj.core.api.Condition<>(str -> str.startsWith("some"), "starts with some"));
        softly.assertThat(success).hasValueSatisfying(str -> assertThat(str).startsWith("some"));
        io.vavr.control.Try<java.lang.String> failure = io.vavr.control.Try.failure(new java.lang.IllegalStateException("not ok"));
        softly.assertThat(failure).isSuccess();
        softly.assertThat(failure).failBecauseOf(java.lang.NullPointerException.class);
        softly.assertThat(failure).failReasonHasMessage("another message");
        io.vavr.control.Either<java.lang.String, java.lang.Integer> right = io.vavr.control.Either.right(2);
        softly.assertThat(right).isLeft();
        softly.assertThat(right).containsOnRight(1);
        softly.assertThat(right).containsRightSame(1);
        softly.assertThat(right).containsRightInstanceOf(java.lang.String.class);
        softly.assertThat(right).hasRightValueSatisfying(v -> assertThat(v).isEqualTo(0));
        softly.assertThat(right).usingValueComparator(java.util.Comparator.naturalOrder()).containsOnRight(3);
        softly.assertThat(right).usingFieldByFieldValueComparator().containsOnRight(3);
        io.vavr.control.Either<java.lang.String, java.lang.Integer> left = io.vavr.control.Either.left("not ok");
        softly.assertThat(left).isRight();
        softly.assertThat(left).containsOnLeft("ok");
        softly.assertThat(left).containsLeftSame("ok");
        softly.assertThat(left).containsLeftInstanceOf(java.lang.Integer.class);
        softly.assertThat(left).hasLeftValueSatisfying(v -> assertThat(v).hasSize(1));
        softly.assertThat(right).usingValueComparator(java.util.Comparator.naturalOrder()).containsOnLeft("ok");
        softly.assertThat(right).usingFieldByFieldValueComparator().containsOnLeft("ok");
        softly.assertThat(io.vavr.collection.HashMap.empty()).isNotEmpty();
        io.vavr.collection.Map<java.lang.String, java.lang.String> map = io.vavr.collection.HashMap.of("Frodo", "Baggins");
        softly.assertThat(map).isEmpty();
        softly.assertThat(map).allSatisfy((key, value) -> {
            assertThat(key).startsWith("key");
            assertThat(value).startsWith("value");
        });
        softly.assertThat(map).containsAnyOf(io.vavr.Tuple.of("Bilbo", "Baggins"));
        softly.assertThat(map).contains(io.vavr.Tuple.of("Peregrin", "Took"));
        softly.assertThat(map).containsAllEntriesOf(io.vavr.collection.List.of(io.vavr.Tuple.of("Bilbo", "Baggins")));
        softly.assertThat(map).containsEntry("Bilbo", "Baggins");
        softly.assertThat(map).containsExactly(io.vavr.Tuple.of("Peregrin", "Took"));
        softly.assertThat(map).containsKey("Peregrin");
        softly.assertThat(map).containsKeys("Peregrin", "Bilbo");
        softly.assertThat(map).containsValue("Took");
        softly.assertThat(map).containsValues("Took", "Brandybuck");
        softly.assertThat(map).doesNotContain(io.vavr.Tuple.of("Frodo", "Baggins"));
        softly.assertThat(map).doesNotContainEntry("Frodo", "Baggins");
        softly.assertThat(map).doesNotContainKey("Frodo");
        softly.assertThat(map).doesNotContainKeys("Frodo");
        softly.assertThat(map).doesNotContainValue("Baggins");
        softly.assertThat(map).doesNotContainValues("Baggins");
        softly.assertThat(map).hasEntrySatisfying("Frodo", new org.assertj.core.api.Condition<>(str -> str.startsWith("some"), "starts with some"));
        softly.assertThat(map).hasSameSizeAs(new java.lang.String[0]);
        softly.assertThat(map).hasSameSizeAs(io.vavr.collection.List.empty());
        softly.assertThat(map).hasSize(0);
        softly.assertThat(map).hasSizeGreaterThan(2);
        softly.assertThat(map).hasSizeLessThan(1);
        softly.assertThat(map).isEqualTo(io.vavr.collection.HashMap.empty());
        softly.assertThat(map).isNotEqualTo(io.vavr.collection.HashMap.of("Frodo", "Baggins"));
        softly.assertThat(map).isNullOrEmpty();
        softly.assertThat(io.vavr.collection.HashMultimap.withSeq().empty()).isNotEmpty();
        io.vavr.collection.Multimap<java.lang.String, java.lang.String> multimap = io.vavr.collection.HashMultimap.withSeq().of("Frodo", "Baggins");
        softly.assertThat(multimap).isEmpty();
        softly.assertThat(multimap).allSatisfy((key, value) -> {
            assertThat(key).startsWith("key");
            assertThat(value).startsWith("value");
        });
        softly.assertThat(multimap).containsAnyOf(io.vavr.Tuple.of("Bilbo", "Baggins"));
        softly.assertThat(multimap).contains(io.vavr.Tuple.of("Peregrin", "Took"));
        softly.assertThat(multimap).containsAllEntriesOf(io.vavr.collection.List.of(io.vavr.Tuple.of("Bilbo", "Baggins")));
        softly.assertThat(multimap).containsEntry("Bilbo", "Baggins");
        softly.assertThat(multimap).containsExactly(io.vavr.Tuple.of("Peregrin", "Took"));
        softly.assertThat(multimap).containsKey("Peregrin");
        softly.assertThat(multimap).containsKeys("Peregrin", "Bilbo");
        softly.assertThat(multimap).containsValue("Took");
        softly.assertThat(multimap).containsValues("Took", "Brandybuck");
        softly.assertThat(multimap).doesNotContain(io.vavr.Tuple.of("Frodo", "Baggins"));
        softly.assertThat(multimap).doesNotContainEntry("Frodo", "Baggins");
        softly.assertThat(multimap).doesNotContainKey("Frodo");
        softly.assertThat(multimap).doesNotContainKeys("Frodo");
        softly.assertThat(multimap).doesNotContainValue("Baggins");
        softly.assertThat(multimap).doesNotContainValues("Baggins");
        softly.assertThat(multimap).hasEntrySatisfying("Frodo", new org.assertj.core.api.Condition<>(str -> str.startsWith("some"), "starts with some"));
        softly.assertThat(multimap).hasSameSizeAs(new java.lang.String[0]);
        softly.assertThat(multimap).hasSameSizeAs(io.vavr.collection.List.empty());
        softly.assertThat(multimap).hasSize(0);
        softly.assertThat(multimap).hasSizeGreaterThan(2);
        softly.assertThat(multimap).hasSizeLessThan(1);
        softly.assertThat(multimap).isEqualTo(io.vavr.collection.HashMap.empty());
        softly.assertThat(multimap).isNotEqualTo(io.vavr.collection.HashMap.of("Frodo", "Baggins"));
        softly.assertThat(multimap).isNullOrEmpty();
    }
}
